import type {
  ActivityEvent,
  Approval,
  FileAsset,
  Mention,
  Membership,
  Note,
  NotificationItem,
  Room,
  SavedView,
  ShareLink,
  Song,
  Task,
  User,
  Version,
  Workspace,
  WorkspaceSnapshot,
} from "./models";

const now = "2026-05-22T18:30:00.000Z";

const ids = {
  workspace: "wsp-amf-private",
  room: "room-secret-album",
  users: {
    theo: "usr-theo",
    alex: "usr-alex",
    river: "usr-river",
    maya: "usr-maya",
    dana: "usr-dana",
  },
};

function waveform(seed: number): number[] {
  return Array.from({ length: 96 }, (_, index) => {
    const value = Math.sin((index + seed) * 0.42) * 0.36 + Math.sin((index + seed) * 0.11) * 0.24 + 0.48;
    return Number(Math.max(0.08, Math.min(0.98, value)).toFixed(2));
  });
}

function asset(
  id: string,
  filename: string,
  durationMs: number,
  lufs: number,
  seed: number,
  stems = false,
  playbackUrl?: string
): FileAsset {
  return {
    asset_id: id,
    workspace_id: ids.workspace,
    original_filename: filename,
    normalized_filename: filename.toLowerCase().replace(/\s+/g, "-"),
    key_original: `originals/${id}.wav`,
    key_flac: `derivatives/${id}.flac`,
    key_aac_256: `derivatives/${id}-256.aac`,
    key_aac_128: `derivatives/${id}-128.aac`,
    key_waveform_json: `waveforms/${id}.json`,
    key_stems_zip: stems ? `stems/${id}.zip` : undefined,
    mime_type: playbackUrl?.endsWith(".m4a") ? "audio/mp4" : (playbackUrl ? "audio/mpeg" : "audio/wav"),
    file_size_bytes: Math.round(durationMs * 92),
    checksum_sha256: `sha256-${id}`,
    duration_ms: durationMs,
    sample_rate: 48000,
    bit_depth: 24,
    loudness_lufs: lufs,
    true_peak_db: -1.2,
    virus_scan_status: "clean",
    transcoding_status: "ready",
    waveform_peaks: waveform(seed),
    playback_url: playbackUrl,
    created_at: now,
  };
}

const users: User[] = [
  {
    user_id: ids.users.theo,
    email: "theo@example.com",
    display_name: "Theo Battaglia",
    two_factor_enabled: true,
    notification_preferences: { mentions: true, listens: false },
    created_at: now,
    updated_at: now,
  },
  {
    user_id: ids.users.alex,
    email: "alex@example.com",
    display_name: "Alex Rivera",
    two_factor_enabled: false,
    notification_preferences: { mentions: true, listens: true },
    created_at: now,
    updated_at: now,
  },
  {
    user_id: ids.users.river,
    email: "river@example.com",
    display_name: "River Vale",
    two_factor_enabled: false,
    notification_preferences: { mentions: true },
    created_at: now,
    updated_at: now,
  },
  {
    user_id: ids.users.maya,
    email: "maya@example.com",
    display_name: "Maya Chen",
    two_factor_enabled: false,
    notification_preferences: { approvals: true },
    created_at: now,
    updated_at: now,
  },
  {
    user_id: ids.users.dana,
    email: "dana@example.com",
    display_name: "Dana Kim",
    two_factor_enabled: false,
    notification_preferences: { inbox: true },
    created_at: now,
    updated_at: now,
  },
];

const workspaces: Workspace[] = [
  {
    workspace_id: ids.workspace,
    name: "White Label · Theo's studio",
    owner_user_id: ids.users.theo,
    plan_type: "producer",
    storage_quota_bytes: 53687091200,
    used_storage_bytes: 1849000000,
    billing_status: "active",
    default_link_policy: { version_policy: "latest_only", watermark_enabled: true },
    default_naming_convention: { strip_tokens: ["v2", "final", "master", "date"] },
    created_at: now,
    updated_at: now,
  },
];

const memberships: Membership[] = [
  { membership_id: "mem-theo", workspace_id: ids.workspace, user_id: ids.users.theo, role: "owner", created_at: now },
  { membership_id: "mem-alex", workspace_id: ids.workspace, user_id: ids.users.alex, role: "engineer", created_at: now },
  { membership_id: "mem-river", workspace_id: ids.workspace, user_id: ids.users.river, role: "artist", created_at: now },
  { membership_id: "mem-maya", workspace_id: ids.workspace, user_id: ids.users.maya, role: "manager", created_at: now },
  { membership_id: "mem-dana", workspace_id: ids.workspace, user_id: ids.users.dana, role: "anr", created_at: now },
];

const rooms: Room[] = [
  {
    room_id: ids.room,
    workspace_id: ids.workspace,
    type: "producer_delivery",
    title: "Hudson Ingram LP · Approval run",
    description: "Private review room — four songs on the approval path before label submission.",
    visibility: "workspace",
    status: "active",
    default_version_visibility: "full_history",
    default_download_policy: "none",
    due_date: "2026-06-07",
    created_by: ids.users.theo,
    created_at: now,
    updated_at: now,
  },
];

const assets: FileAsset[] = [
  // The First Night — Hudson Ingram x PomPom (v1 pitch from Aug 2023, v2 working)
  asset("asset-midnight-v1", "the-first-night_v1_pitch_pompom.mp3", 191000, -10.8, 1, false, "/seed-audio/the-first-night-v1-pitch.mp3"),
  asset("asset-midnight-v2", "the-first-night_v2_pompom.mp3",        214000, -14.1, 2, false, "/seed-audio/the-first-night-v2.mp3"),
  asset("asset-midnight-v3", "austin-again_v4_pre-mix.mp3",          277000,  -9.2, 3, false, "/seed-audio/austin-again-v4.mp3"),
  // Lighting The Fuse — Hudson Ingram x Liz Rose
  asset("asset-neon-v1", "prom-queen_v1.2_with-strings.mp3",         241000, -16.1, 4, false, "/seed-audio/prom-queen-v1.mp3"),
  asset("asset-neon-v2", "lighting-the-fuse_v2_liz-rose-cowrite.mp3", 231000, -13.6, 5, false, "/seed-audio/lighting-the-fuse-v2.mp3"),
  asset("asset-neon-v3", "just-like-you_v2_jensen-mcrae.mp3",         256000, -11.9, 6, false, "/seed-audio/just-like-you-v2.mp3"),
  // Duel — Ruby Plume (v5)
  asset("asset-witness-v1", "duel_v5_ruby-plume.m4a",       182000, -15.4, 7, false, "/seed-audio/duel-v5.m4a"),
  asset("asset-witness-v2", "duel_v5_master-print.m4a",     182000, -12.8, 8, false, "/seed-audio/duel-v5.m4a"),
  asset("asset-witness-clean", "best-of-me_demo-v2_117bpm.mp3", 499000, -12.7, 9, false, "/seed-audio/best-of-me-v2.mp3"),
  // Best Of Me — Daniel Price · Olmo · Mills (v2 demo, 117 bpm)
  asset("asset-lowlight-v1", "best-of-me_demo-v2.mp3",      499000, -15.9, 10, false, "/seed-audio/best-of-me-v2.mp3"),
  asset("asset-lowlight-v2", "best-of-me_demo-v2_alt.mp3",  499000, -13.2, 11, false, "/seed-audio/best-of-me-v2.mp3"),
  asset("asset-lowlight-inst", "best-of-me_inst-v1.mp3",    499000, -13.4, 12, true,  "/seed-audio/best-of-me-v2.mp3"),
];

const songs: Song[] = [
  {
    song_id: "song-midnight",
    workspace_id: ids.workspace,
    primary_room_id: ids.room,
    title: "The First Night",
    artist_display_name: "Hudson Ingram",
    project_name: "Hudson Ingram LP",
    status: "revision_requested",
    current_version_id: "ver-midnight-v2",
    approved_version_id: undefined,
    bpm: 92,
    song_key: "F minor",
    explicit_flag: true,
    genre_tags: ["alt-pop", "electronic"],
    mood_tags: ["humid", "late-night"],
    instrument_tags: ["808", "juno pad"],
    lyric_theme_tags: ["distance"],
    release_readiness_status: "not_ready",
    created_by: ids.users.theo,
    created_at: now,
    updated_at: now,
  },
  {
    song_id: "song-neon",
    workspace_id: ids.workspace,
    primary_room_id: ids.room,
    title: "Lighting The Fuse",
    artist_display_name: "Hudson Ingram",
    project_name: "Hudson Ingram LP",
    status: "in_review",
    current_version_id: "ver-neon-v3",
    approved_version_id: undefined,
    bpm: 118,
    song_key: "A major",
    explicit_flag: false,
    genre_tags: ["dance", "pop"],
    mood_tags: ["bright", "urgent"],
    instrument_tags: ["guitar", "drum machine"],
    lyric_theme_tags: ["leaving"],
    release_readiness_status: "not_ready",
    created_by: ids.users.theo,
    created_at: now,
    updated_at: now,
  },
  {
    song_id: "song-witness",
    workspace_id: ids.workspace,
    primary_room_id: ids.room,
    title: "Duel",
    artist_display_name: "Ruby Plume",
    project_name: "Ruby Plume single",
    status: "approved",
    current_version_id: "ver-witness-clean",
    approved_version_id: "ver-witness-clean",
    bpm: 76,
    song_key: "D minor",
    explicit_flag: true,
    genre_tags: ["ballad", "cinematic"],
    mood_tags: ["wide", "raw"],
    instrument_tags: ["piano", "strings"],
    lyric_theme_tags: ["repair"],
    release_readiness_status: "not_ready",
    created_by: ids.users.theo,
    created_at: now,
    updated_at: now,
  },
  {
    song_id: "song-lowlight",
    workspace_id: ids.workspace,
    primary_room_id: ids.room,
    title: "Best Of Me",
    artist_display_name: "Daniel Price · Olmo · Mills",
    project_name: "Daniel Price · EP",
    status: "in_progress",
    current_version_id: "ver-lowlight-inst",
    approved_version_id: undefined,
    bpm: 101,
    song_key: "C# minor",
    explicit_flag: false,
    genre_tags: ["r&b", "minimal"],
    mood_tags: ["close", "smoked"],
    instrument_tags: ["rhodes", "sub"],
    lyric_theme_tags: ["memory"],
    release_readiness_status: "not_ready",
    created_by: ids.users.theo,
    created_at: now,
    updated_at: now,
  },
];

const versions: Version[] = [
  {
    version_id: "ver-midnight-v1",
    song_id: "song-midnight",
    version_number: 1,
    version_label: "Mix v1",
    type: "mix",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-midnight-v1",
    created_at: "2026-05-21T16:00:00.000Z",
  },
  {
    version_id: "ver-midnight-v2",
    song_id: "song-midnight",
    version_number: 2,
    version_label: "Mix v2",
    type: "mix",
    parent_version_id: "ver-midnight-v1",
    is_current: true,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-midnight-v2",
    created_at: "2026-05-22T16:00:00.000Z",
  },
  {
    version_id: "ver-midnight-v3",
    song_id: "song-midnight",
    version_number: 3,
    version_label: "Master v3",
    type: "master",
    parent_version_id: "ver-midnight-v2",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-midnight-v3",
    created_at: "2026-05-22T17:00:00.000Z",
  },
  {
    version_id: "ver-neon-v1",
    song_id: "song-neon",
    version_number: 1,
    version_label: "Demo v1",
    type: "demo",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.theo,
    file_asset_id: "asset-neon-v1",
    created_at: now,
  },
  {
    version_id: "ver-neon-v2",
    song_id: "song-neon",
    version_number: 2,
    version_label: "Rough v2",
    type: "rough",
    parent_version_id: "ver-neon-v1",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-neon-v2",
    created_at: now,
  },
  {
    version_id: "ver-neon-v3",
    song_id: "song-neon",
    version_number: 3,
    version_label: "Mix v3",
    type: "mix",
    parent_version_id: "ver-neon-v2",
    is_current: true,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-neon-v3",
    created_at: now,
  },
  {
    version_id: "ver-witness-v1",
    song_id: "song-witness",
    version_number: 1,
    version_label: "Mix v1",
    type: "mix",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-witness-v1",
    created_at: now,
  },
  {
    version_id: "ver-witness-v2",
    song_id: "song-witness",
    version_number: 2,
    version_label: "Mix v2",
    type: "mix",
    parent_version_id: "ver-witness-v1",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-witness-v2",
    created_at: now,
  },
  {
    version_id: "ver-witness-clean",
    song_id: "song-witness",
    version_number: 3,
    version_label: "Clean v3",
    type: "clean",
    parent_version_id: "ver-witness-v2",
    is_current: true,
    is_approved: true,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-witness-clean",
    created_at: now,
  },
  {
    version_id: "ver-lowlight-v1",
    song_id: "song-lowlight",
    version_number: 1,
    version_label: "Mix v1",
    type: "mix",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-lowlight-v1",
    created_at: now,
  },
  {
    version_id: "ver-lowlight-v2",
    song_id: "song-lowlight",
    version_number: 2,
    version_label: "Mix v2",
    type: "mix",
    parent_version_id: "ver-lowlight-v1",
    is_current: false,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-lowlight-v2",
    created_at: now,
  },
  {
    version_id: "ver-lowlight-inst",
    song_id: "song-lowlight",
    version_number: 3,
    version_label: "Instrumental v3",
    type: "instrumental",
    parent_version_id: "ver-lowlight-v2",
    is_current: true,
    is_approved: false,
    uploaded_by: ids.users.alex,
    file_asset_id: "asset-lowlight-inst",
    created_at: now,
  },
];

const notes: Note[] = [
  {
    note_id: "note-vocal-delay",
    song_id: "song-midnight",
    anchor_version_id: "ver-midnight-v1",
    room_id: ids.room,
    author_user_id: ids.users.river,
    body: "Vocal delay too loud here @Alex.",
    scope: "song",
    visibility: "everyone",
    timestamp_start_ms: 72000,
    timestamp_uncertain: false,
    assigned_to_user_id: ids.users.alex,
    priority: "high",
    status: "open",
    created_at: "2026-05-21T16:12:00.000Z",
    updated_at: "2026-05-21T16:12:00.000Z",
  },
  {
    note_id: "note-kick-fixed",
    song_id: "song-midnight",
    anchor_version_id: "ver-midnight-v1",
    room_id: ids.room,
    author_user_id: ids.users.maya,
    body: "Kick pokes too hard entering the second hook.",
    scope: "song",
    visibility: "everyone",
    timestamp_start_ms: 132000,
    timestamp_uncertain: false,
    assigned_to_user_id: ids.users.alex,
    priority: "normal",
    status: "resolved",
    resolved_by: ids.users.alex,
    resolved_at: "2026-05-22T16:18:00.000Z",
    resolved_on_version_id: "ver-midnight-v2",
    created_at: "2026-05-21T16:19:00.000Z",
    updated_at: "2026-05-22T16:18:00.000Z",
  },
  {
    note_id: "note-neon-private",
    song_id: "song-neon",
    anchor_version_id: "ver-neon-v3",
    room_id: ids.room,
    author_user_id: ids.users.dana,
    body: "Private: strong hook, needs shorter intro for pitch.",
    scope: "version",
    visibility: "private",
    timestamp_start_ms: 34000,
    timestamp_uncertain: false,
    priority: "normal",
    status: "open",
    created_at: now,
    updated_at: now,
  },
];

const mentions: Mention[] = [
  {
    mention_id: "mention-alex-delay",
    note_id: "note-vocal-delay",
    mentioned_user_id: ids.users.alex,
    notification_status: "delivered",
    created_at: "2026-05-21T16:12:01.000Z",
  },
];

const approvals: Approval[] = [
  {
    approval_id: "approval-witness",
    version_id: "ver-witness-clean",
    actor_user_id: ids.users.river,
    state: "approved",
    note: "Approved current clean mix.",
    created_at: now,
  },
];

const shareLinks: ShareLink[] = [
  {
    link_id: "link-room-current",
    workspace_id: ids.workspace,
    target_type: "room",
    target_id: ids.room,
    token_hash: "demo-room-token-hash",
    demo_token: "room-demo",
    link_name: "Artist + manager latest room",
    access_mode: "identity_required",
    download_policy: "none",
    version_policy: "latest_only",
    requires_identity: true,
    watermark_enabled: true,
    allow_comments: true,
    allow_approval: true,
    allow_forwarding: false,
    created_by: ids.users.theo,
    created_at: "2026-05-21T16:05:00.000Z",
  },
  {
    link_id: "link-dana-history",
    workspace_id: ids.workspace,
    target_type: "song",
    target_id: "song-neon",
    token_hash: "demo-dana-token-hash",
    demo_token: "dana-neon",
    link_name: "Dana full history",
    access_mode: "public",
    download_policy: "current",
    version_policy: "full_history",
    requires_identity: false,
    watermark_enabled: true,
    allow_comments: true,
    allow_approval: false,
    allow_forwarding: true,
    created_by: ids.users.maya,
    created_at: now,
  },
];

const activityEvents: ActivityEvent[] = [
  {
    event_id: "evt-upload-1",
    workspace_id: ids.workspace,
    actor_user_id: ids.users.alex,
    event_type: "uploaded_version",
    target_type: "version",
    target_id: "ver-midnight-v1",
    song_id: "song-midnight",
    version_id: "ver-midnight-v1",
    metadata: { filename: "Midnight Weather mix v1.wav" },
    created_at: "2026-05-21T16:00:00.000Z",
  },
  {
    event_id: "evt-comment-delay",
    workspace_id: ids.workspace,
    actor_user_id: ids.users.river,
    event_type: "commented",
    target_type: "note",
    target_id: "note-vocal-delay",
    song_id: "song-midnight",
    version_id: "ver-midnight-v1",
    link_id: "link-room-current",
    metadata: { timestamp_ms: 72000 },
    created_at: "2026-05-21T16:12:00.000Z",
  },
  {
    event_id: "evt-mention-alex",
    workspace_id: ids.workspace,
    actor_user_id: ids.users.river,
    event_type: "mentioned_user",
    target_type: "note",
    target_id: "note-vocal-delay",
    song_id: "song-midnight",
    version_id: "ver-midnight-v1",
    metadata: { mentioned_user_id: ids.users.alex },
    created_at: "2026-05-21T16:12:01.000Z",
  },
  {
    event_id: "evt-upload-2",
    workspace_id: ids.workspace,
    actor_user_id: ids.users.alex,
    event_type: "uploaded_version",
    target_type: "version",
    target_id: "ver-midnight-v2",
    song_id: "song-midnight",
    version_id: "ver-midnight-v2",
    metadata: { prior_version_id: "ver-midnight-v1" },
    created_at: "2026-05-22T16:00:00.000Z",
  },
  {
    event_id: "evt-manager-play-v2",
    workspace_id: ids.workspace,
    actor_user_id: ids.users.maya,
    event_type: "played_track",
    target_type: "version",
    target_id: "ver-midnight-v2",
    song_id: "song-midnight",
    version_id: "ver-midnight-v2",
    link_id: "link-room-current",
    metadata: { heard_ms: 164000 },
    created_at: "2026-05-22T16:30:00.000Z",
  },
  {
    event_id: "evt-approval",
    workspace_id: ids.workspace,
    actor_user_id: ids.users.river,
    event_type: "approved_version",
    target_type: "version",
    target_id: "ver-witness-clean",
    song_id: "song-witness",
    version_id: "ver-witness-clean",
    metadata: {},
    created_at: now,
  },
];

const tasks: Task[] = [
  {
    task_id: "task-delay",
    workspace_id: ids.workspace,
    room_id: ids.room,
    song_id: "song-midnight",
    version_id: "ver-midnight-v1",
    source_note_id: "note-vocal-delay",
    title: "Tame vocal delay at 1:12",
    assigned_to_user_id: ids.users.alex,
    status: "open",
    priority: "high",
    created_by: ids.users.river,
    created_at: "2026-05-21T16:12:30.000Z",
    updated_at: "2026-05-21T16:12:30.000Z",
  },
];

const notifications: NotificationItem[] = [
  {
    notification_id: "notif-delay",
    user_id: ids.users.alex,
    type: "mention",
    payload: { song_id: "song-midnight", version_id: "ver-midnight-v1", timestamp_ms: 72000 },
    created_at: "2026-05-21T16:12:01.000Z",
  },
];

const savedViews: SavedView[] = [
  {
    view_id: "view-missing-deliverables",
    workspace_id: ids.workspace,
    user_id: ids.users.maya,
    name: "Approved & missing deliverables",
    filter: { status: "approved", missing: ["instrumental", "stems"] },
    created_at: now,
  },
  {
    view_id: "view-public-links",
    workspace_id: ids.workspace,
    user_id: ids.users.theo,
    name: "Public links older than 7 days",
    filter: { access_mode: "public", min_age_days: 7 },
    created_at: now,
  },
];

export function createSeedSnapshot(): WorkspaceSnapshot {
  return structuredClone({
    workspaces,
    users,
    memberships,
    rooms,
    assets,
    songs,
    versions,
    notes,
    mentions,
    tasks,
    approvals,
    shareLinks,
    activityEvents,
    notifications,
    savedViews,
  });
}

